IP_URL = 'https://api64.ipify.org?format=json'
IP_GEO_URL = 'http://ip-api.com/json/'
GEOCODE_URL = 'https://positionstack.com/geo_api.php'
MUSLIMPRO_URL = 'https://www.muslimpro.com/find'
CONF_PATH = 'main\config.ini'